version: '3.9'

services:
  intergg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: intergg_bot
    environment:
      INTER_DB: "/data/intergg.sqlite"
    volumes:
      - ./data:/data
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      - migrate

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head
    volumes:
      - ./data:/data
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      INTER_DB: "/data/intergg.sqlite"