services:
  intergg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: intergg_bot
    environment:
      INTER_DB: "/data/intergg.sqlite"
    volumes:
      - ./data:/data
