"""Add ranked fields with defaults

Revision ID: 21e3ec6c4a0b
Revises: 13f59b4cdddd
Create Date: 2025-06-13 21:18:12.574508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e3ec6c4a0b'
down_revision: Union[str, None] = '13f59b4cdddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('solo_tier', sa.String(), server_default='Unranked', nullable=False))
    op.add_column('user_account', sa.Column('solo_rank', sa.String(), server_default='Unranked', nullable=False))
    op.add_column('user_account', sa.Column('solo_league_points', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_account', sa.Column('flex_tier', sa.String(), server_default='Unranked', nullable=False))
    op.add_column('user_account', sa.Column('flex_rank', sa.String(), server_default='Unranked', nullable=False))
    op.add_column('user_account', sa.Column('flex_league_points', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('user_account', 'division_solo')
    op.drop_column('user_account', 'league_points_flex')
    op.drop_column('user_account', 'tier_flex')
    op.drop_column('user_account', 'league_points_solo')
    op.drop_column('user_account', 'division_flex')
    op.drop_column('user_account', 'tier_solo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('tier_solo', sa.VARCHAR(), nullable=False))
    op.add_column('user_account', sa.Column('division_flex', sa.VARCHAR(), nullable=False))
    op.add_column('user_account', sa.Column('league_points_solo', sa.INTEGER(), nullable=False))
    op.add_column('user_account', sa.Column('tier_flex', sa.VARCHAR(), nullable=False))
    op.add_column('user_account', sa.Column('league_points_flex', sa.INTEGER(), nullable=False))
    op.add_column('user_account', sa.Column('division_solo', sa.VARCHAR(), nullable=False))
    op.drop_column('user_account', 'flex_league_points')
    op.drop_column('user_account', 'flex_rank')
    op.drop_column('user_account', 'flex_tier')
    op.drop_column('user_account', 'solo_league_points')
    op.drop_column('user_account', 'solo_rank')
    op.drop_column('user_account', 'solo_tier')
    # ### end Alembic commands ###
